#ifndef _EV_CAN_LIST_H_
#define _EV_CAN_LIST_H_

#include "vifManagerService/LGE_CANSignalFrameID.h"

using namespace SignalFrame_PMZ_e;
uint16_t EVT_Frame_Monitoring_List[] = {
    SignalFrame_GWM_PMZ_AD_Hybrid_RX,
    SignalFrame_GWM_PMZ_R_Hybrid_RX,
    SignalFrame_GWM_PMZ_S_Hybrid_RX,
    SignalFrame_GWM_PMZ_T_Hybrid_RX,
    SignalFrame_GWM_PMZ_U_Hybrid_RX,
    SignalFrame_PCM_PMZ_Q_Hybrid_RX,
    SignalFrame_PCM_PMZ_S_Hybrid_RX
    // Need to more!!
};

uint16_t EVT_CAN_Monitoring_List[] = {
    Signal_TimedCharge1Active_RX,
    Signal_TimedCharge1ActiveFri_RX,
    Signal_TimedCharge1ActiveMon_RX,
    Signal_TimedCharge1ActiveSat_RX,
    Signal_TimedCharge1ActiveSun_RX,
    Signal_TimedCharge1ActiveThur_RX,
    Signal_TimedCharge1ActiveTues_RX,
    Signal_TimedCharge1ActiveWed_RX,
    Signal_TimedCharge1EndTimeA_RX,
    Signal_TimedCharge1EndTimeB_RX,
    Signal_TimedCharge1EndTimeC_RX,
    Signal_TimedCharge1EndTimeD_RX,
    Signal_TimedCharge1ZoneA_RX,
    Signal_TimedCharge1ZoneB_RX,
    Signal_TimedCharge1ZoneC_RX,
    Signal_TimedCharge1ZoneD_RX,
    Signal_TimedCharge1ZoneE_RX,
    Signal_TimedCharge2Active_RX,
    Signal_TimedCharge2ActiveFri_RX,
    Signal_TimedCharge2ActiveMon_RX,
    Signal_TimedCharge2ActiveSat_RX,
    Signal_TimedCharge2ActiveSun_RX,
    Signal_TimedCharge2ActiveThur_RX,
    Signal_TimedCharge2ActiveTues_RX,
    Signal_TimedCharge2ActiveWed_RX,
    Signal_TimedCharge2EndTimeA_RX,
    Signal_TimedCharge2EndTimeB_RX,
    Signal_TimedCharge2EndTimeC_RX,
    Signal_TimedCharge2EndTimeD_RX,
    Signal_TimedCharge2ZoneA_RX,
    Signal_TimedCharge2ZoneB_RX,
    Signal_TimedCharge2ZoneC_RX,
    Signal_TimedCharge2ZoneD_RX,
    Signal_TimedCharge2ZoneE_RX,
    Signal_TimedCharge3Active_RX,
    Signal_TimedCharge3ActiveFri_RX,
    Signal_TimedCharge3ActiveMon_RX,
    Signal_TimedCharge3ActiveSat_RX,
    Signal_TimedCharge3ActiveSun_RX,
    Signal_TimedCharge3ActiveThur_RX,
    Signal_TimedCharge3ActiveTues_RX,
    Signal_TimedCharge3ActiveWed_RX,
    Signal_TimedCharge3EndTimeA_RX,
    Signal_TimedCharge3EndTimeB_RX,
    Signal_TimedCharge3EndTimeC_RX,
    Signal_TimedCharge3EndTimeD_RX,
    Signal_TimedCharge3ZoneA_RX,
    Signal_TimedCharge3ZoneB_RX,
    Signal_TimedCharge3ZoneC_RX,
    Signal_TimedCharge3ZoneD_RX,
    Signal_TimedCharge3ZoneE_RX,
    Signal_TimedCharge4Active_RX,
    Signal_TimedCharge4ActiveFri_RX,
    Signal_TimedCharge4ActiveMon_RX,
    Signal_TimedCharge4ActiveSat_RX,
    Signal_TimedCharge4ActiveSun_RX,
    Signal_TimedCharge4ActiveThur_RX,
    Signal_TimedCharge4ActiveTues_RX,
    Signal_TimedCharge4ActiveWed_RX,
    Signal_TimedCharge4EndTimeA_RX,
    Signal_TimedCharge4EndTimeB_RX,
    Signal_TimedCharge4EndTimeC_RX,
    Signal_TimedCharge4EndTimeD_RX,
    Signal_TimedCharge4ZoneA_RX,
    Signal_TimedCharge4ZoneB_RX,
    Signal_TimedCharge4ZoneC_RX,
    Signal_TimedCharge4ZoneD_RX,
    Signal_TimedCharge4ZoneE_RX,
    Signal_BulkSoCTargetDisp_RX,
    Signal_ChargeNowRequest_RX,
    Signal_ChargingModeChoice_RX,
    Signal_FirstTimeChargeSetStat_RX,
    Signal_Timer1Time_RX,
    Signal_Timer2Time_RX,
    Signal_ParkHeatVentTime_RX,
    Signal_AmbTempImpr_RX,
    Signal_ParkClimateMode_RX,
    Signal_ParkClimateStatus_RX,
    // Signal_InCarTemp_RX,     // Not used
    // Signal_InCarTempQF_RX,   // Not used
    Signal_ChargDataWakeUpAllowed_RX,
    Signal_ChargePwrInterruptDisp_RX,
    Signal_ChargingStatusDisp_RX,
    Signal_HybridStatusMsgDisp_RX,
    Signal_kWhConsumedLastCharge_RX,
    Signal_kWhConsumedperKm_RX,
    Signal_TimeToFullSoC_RX,
    Signal_ChargeReminderDisp_RX,
    Signal_ChrgNotReadyByDepDisp_RX,
    Signal_HVBattChargeRateKmDisp_RX,
    Signal_HVBattChrgeRateSOCDisp_RX,
    Signal_HVBatteryUsableKmDisp_RX,
    Signal_HVBatteryUsableSOCDisp_RX,
    Signal_HybridPluginDisp_RX,
    Signal_EVRangeSelectedSOC_RX,
    Signal_EVRangeComfort_RX,
    Signal_EVRangeDynamic_RX,
    Signal_EVRangeEco_RX,
    Signal_EVRangeGetMeHome_RX,
    Signal_EVRangePredictStatus_RX,
    Signal_TimeToBulkSoC_RX,
    Signal_WlChargingStatusDisp_RX,
    // Signal_VehicleConfParameters_RX,
    // Signal_VehicleInfoParametersPMZ_RX,
    // Signal_VehicleInfoParametersBO_RX,
    // Signal_CrashTypeRollVDM_RX,    // CM 20151013 This is only for MultiCAN
    // //   Signal_ChargingModeChoice_RX,      // start : add 2016.03.08.
    Signal_PreDepTimeActFri_RX,
    Signal_PreDepTimeActive_RX,
    Signal_PreDepTimeActMon_RX,
    Signal_PreDepTimeActSat_RX,
    Signal_PreDepTimeActSun_RX,
    Signal_PreDepTimeActThu_RX,
    Signal_PreDepTimeActTue_RX,
    Signal_PreDepTimeActWed_RX,
    Signal_PreDepTimeDate_RX,
    Signal_PreDepTimeHour_RX,
    Signal_PreDepTimeIndex_RX,
    Signal_PreDepTimeMins_RX,
    Signal_PreDepTimeMnth_RX,
    Signal_PreDepTimeType_RX,
    Signal_PreDepTimeYear_RX,
    Signal_NextPresetDepTimeDate_RX,
    Signal_NextPresetDepTimeHour_RX,
    Signal_NextPresetDepTimeMins_RX,
    Signal_NextPresetDepTimeMnth_RX,
    Signal_NextPresetDepTimeYear_RX,
    Signal_BulkSoCSingleUseDisp_RX,
    Signal_PasSeatInhib1stRow_RX,
    Signal_PasSeatPosition1stRow_RX,
    Signal_FFHPreClimSetting_RX,
    Signal_HVBattCoolingStatus_RX,
    Signal_HVBattHeatingStatus_RX,
    Signal_PreClimRangeComfort_RX,
    Signal_PreClimateRequests_RX,
    Signal_PreClimateStatus_RX,
    Signal_HVBattChrgRateMileDisp_RX,
    Signal_EVRangeMilesDisp_RX,
    //   Signal_TimeToFullSoC_RX,
    //   Signal_HVBatteryUsableKmDisp_RX,
    Signal_EVRangeDisp_RX,
    Signal_VSCRangeOnRouteFlag_RX,
    Signal_EVRangeSelectSOCMiles_RX,
    Signal_TimeToBulkSoCHoursDisp_RX,
    Signal_TimeToBulkSoCMinsDisp_RX,
    Signal_TimeToFullSoCHoursDisp_RX,
    Signal_TimeToFullSoCMinsDisp_RX,
    Signal_CombinedRangeDisp_RX,
    Signal_CombinedRangeMilesDisp_RX,
    Signal_TimedChrgStartDateDisp_RX,
    Signal_TimedChrgStartHourDisp_RX,
    Signal_TimedChrgStartMinsDisp_RX,
    Signal_TimedChrgStartMnthDisp_RX,
    Signal_TimedChrgStartYearDisp_RX,
    Signal_FFHOperatingStatus_RX,
    Signal_HVBattCoolingStatusExt_RX,
    Signal_VSCHVBattConsumpSpd1_RX,
    Signal_VSCHVBattConsumpSpd2_RX,
    Signal_VSCHVBattConsumpSpd3_RX,
    Signal_VSCHVBattConsumpSpd4_RX,
    Signal_VSCHVBattConsumpSpd5_RX,
    Signal_VSCHVBattConsumpSpd6_RX,
    Signal_VSCHVBattConsumpSpd7_RX,
    Signal_VSCHVEnergyAscent_RX,
    Signal_VSCHVEnergyDescent_RX,
    Signal_VSCHVEnergyTimePen_RX,
    Signal_VSCInitialHVBattEnergy_RX,
    Signal_VSCRangeMapRefactrComf_RX,
    Signal_VSCRangeMapRefactrEco_RX,
    Signal_VSCRangeMapRefactrGMH_RX,
    Signal_VSCRegenEnergyAvailable_RX,
    Signal_VSCRegenEnergyFactor_RX,
    Signal_VSCRevisedHVBattEnergy_RX,
    Signal_VSCVehAccelFactor_RX,            // end : add release7
    Signal_ChargePlugDiscAlarmReq_RX,       // start : add release8. 2016.11.14. NCR31
    //Signal_HVBattCellVoltageMax_RX,
    //Signal_HVBattCellVoltageMin_RX,
    //Signal_HVBattCurrentExt_RX,
    //Signal_HVBattVoltageExt_RX,
    Signal_HVBattAvgSOCOAtEvent_RX,
    Signal_HVBattAvTempAtEvent_RX,
    //Signal_HVBattFastChgCounter_RX,
    Signal_HVBattLogEvent_RX,
    //Signal_HVBattTempColdCellID_RX,
    //Signal_HVBattTempHottCellID_RX,
    //Signal_HVBattVoltMaxCellID_RX,
    //Signal_HVBattVoltMinCellID_RX,
    // >>>>>>>>>>>>>>>>>>>>>>>>>> Only for CHN EV
    // Signal_DCDCOperatingModeExt_RX,
    // Signal_DCDCTemperature_RX,
    // Signal_EMOperatingModeExt_RX,
    // Signal_EMOperatingModeF_RX,
    // Signal_EMSpeed_RX,
    // Signal_EMSpeedF_RX,
    // Signal_InverterTemperature_RX,
    // Signal_InverterTemperatureF_RX,
    // Signal_EMCurrentDcLink_RX,
    // Signal_EMCurrentDCLinkF_RX,
    // Signal_EMTemperature_RX,
    // Signal_EMTemperatureF_RX,
    // Signal_EMTorqueExt_RX,
    // Signal_EMTorqueF_RX,
    // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    Signal_ChargeNowRequestExt_RX,
    //Signal_HVBattVoltageExt_RX,   // PCR027 HBD DOTA(17W04)
    //Signal_HVBattCurrentExt_RX,
    //Signal_HVBattCellVoltageMax_RX,
    //Signal_HVBattVoltMaxCellID_RX,
    //Signal_HVBattCellVoltageMin_RX,
    //Signal_HVBattVoltMinCellID_RX,
    //Signal_HVBattCellTempHottest_RX,
    //Signal_HVBattTempHottCellID_RX,
    Signal_HVBattCellTempColdest_RX,
    //Signal_HVBattTempColdCellID_RX,
    //Signal_HVBattStatusCAT4Derate_RX,
    //Signal_HVBattStatusCAT6DlyBPO_RX,
    //Signal_HVBattStatusCAT7NowBPO_RX,
    //Signal_HVBattStateofHealth_RX,
    //Signal_HVBattStateofHealthMin_RX,
    //Signal_HVBattStateofHealthMax_RX,
    //Signal_HVBattStateofHealthPwr_RX,
    //Signal_HVBattSoHcMinCellID_RX,
    //Signal_HVBattSoHcMaxCellID_RX,
    //Signal_HVBattFastChgCounter_RX,
    //Signal_HVBattInletCoolantTemp_RX,
    //Signal_HVBattOutletCoolantTmp_RX,
    //Signal_HVBattCoolingEnrgyUsd_RX,
    //Signal_HVBattThrmlMngrMode_RX,
    //Signal_HVBattBalancingStatus_RX,
    //Signal_HVBattBlncngTrgrCellID_RX,
    //Signal_HVBattFuseTemperature_RX,
    //Signal_HVBattBEMTemperature_RX,
    Signal_AmbientTemp_RX,
    Signal_HVBattAvgSOCOAtEvent_RX,
    Signal_HVBattAvTempAtEvent_RX,
    Signal_WirelessConnectStatus_RX// END
};
#endif // _EV_CAN_LIST_H_
