#include "EvConfigReceiver.h"
#include "EvDebugReceiver.h"
#include "EvDiagReceiver.h"
#include "EvNgtpReceiver.h"
#include "EvPowerModeReceiver.h"
#include "EvPowerStateReceiver.h"
#include "EvVifReceiver.h"