/**
* \file    RS_EVENT_LIST.h
* \brief     Definition of RemoteService event.
*
* \details
*    This software is copyright protected and proprietary to
*    LG electronics. LGE grants to you only those rights as
*    set out in the license conditions. All other rights remain
*    with LG electronics.
* \author       dongjin1.seo
* \date    2015.06.25
* \attention Copyright (c) 2015 by LG electronics co, Ltd. All rights reserved.
*/

#ifndef _REMOTE_SERVICE_EVENT_H_
#define _REMOTE_SERVICE_EVENT_H_

enum RS_EVENT {
    RES_RECV_ENGINE_START_E = 0,
    RES_RECV_ENGINE_STOP_E,
    RES_SEND_TCU_PREREQ_STATUS_E,
    RES_SEND_TCU_BCM_AUTH_STATUS_E,
    RES_SEND_ENGINE_START_STATUS_E,
    RES_FFH_OPERATE_STATUS_E,
    RES_REQ_ENGINE_START_E,
    RES_REQ_ENGINE_STOP_E,
    RES_RESP_ENGINE_START_STATUS_E,
    RES_RESP_ENGINE_STOP_STATUS_E,
    RES_RESP_TCU_BCM_AUTH_STATUS_E,
    RES_RES_SEQUENCE_STATUS_CHANGED_E,
    RES_PARK_CLIMATE_MODE_CHANGED_E,
    RES_REQ_BCM_PREREQ_STATUS_E,
    RES_PREREQ_RESPONSE_TIME_EXPIRE_E,
    RES_FFH_RUN_TIME_MAX_EXPIRE_E,
    RES_ENG_START_TIME_EXPIRE_E,
    RES_ENG_STOP_TIME_EXPIRE_E,
    RES_RUN_TIME_LENGTH_EXPIRE_E,
    RES_PARK_CLIMATE_STARTUP_TIME_EXPIRE_E,
    RES_SEND_ENGINE_STOP_STATUS,
    RCC_RECV_CLIMATE_CONTROL_START_E,
    RCC_SEND_CLIMATE_CONTROL_START_STATUS_E,
    RCC_SEND_CLIMATE_SYSTEM_STATUS_E,
    RCC_REQ_CLIMATE_CONTROL_START_E,
    RCC_RECV_CLIMATE_DISABLE_REQ_E,
    RCC_RECV_HEATED_SEAT_CONTROL_E,
    RCC_RECV_HEATED_SEAT_STATUS_E,
    RCC_RECV_DEFROST_STATUS_E,
    RCC_RECV_HEATED_SCREEN_STATUS_E,
    RPC_RECV_PARK_CLIMATE_VENTING_START_E,
    RPC_RECV_PARK_CLIMATE_HEATING_START_E,
    RPC_RECV_PARK_CLIMATE_AUTO_START_E,
    RPC_RECV_PARK_CLIMATE_STOP_E,
    RPC_SEND_PARK_CLIMATE_INVOKE_STATUS_E,
    RVI_RECV_VEHICLE_UNLOCK_E,
    RVI_RECV_VEHICLE_SECURE_E,
    RVI_RECV_ALARM_RESET_E,
    RVI_RECV_LOCATION_CHECK_E,
    RVI_SEND_TCU_BCM_AUTH_STATUS_E,
    RVI_SEND_VEHICLE_UNLOCK_STATUS_E,
    RVI_SEND_VEHICLE_SECURE_STATUS_E,
    RVI_SEND_ALARM_RESET_STATUS_E,
    RISM_RECV_SEAT_MOVE_FOLD_E,
    RISM_RECV_SEAT_MOVE_UNFOLD_E,
    RISM_RECV_SEAT_MOVE_CANCEL_E,
    RISM_SEND_TCU_BCM_AUTH_STATUS_E,
    RISM_SEND_SEAT_MOVE_FOLD_STATUS_E,
    RISM_SEND_SEAT_MOVE_UNFOLD_STATUS_E,
    RISM_SEND_SEAT_MOVE_CANCEL_STATUS_E,
    RISM_REQ_INIT_SEAT_MOVE_E,
    RISM_REQ_COMPLETE_SEAT_MOVE_E,
    RISM_RESP_INIT_SEAT_MOVE_STATUS_E,
    RISM_REQ_SEAT_MOVE_FOLD_E,
    RISM_REQ_SEAT_MOVE_UNFOLD_E,
    RISM_REQ_SEAT_MOVE_CANCEL_E,
    RS_EVENT_LIST_MAX
};
#endif /**_REMOTE_SERVICE_EVENT_H_*/